### ISSUE TITLE
we install influxDB + grafana in the same instance or separate ? 

### ISSUE THREAD

**Issue by cuongngosa** [Nordstrom/serverless-artillery-workshop#10]
How cost about that ?

**Comment by erikerikson** [comment]
I believe we did install them on the same server.
paging @gwsii

**Comment by gwsii** [comment]
@cuongngosa InfluxDB and Grafana are distinct applications, i.e. Grafana can be configured to consume many different kinds of data sources, IndluxDB is among them.

Either configuration (shared instance vs. each running on their own instance) should work.

Please see the documentation on InfluxDB and Grafana for more information. For Artillery, we use the [artillery-plugin-influxdb](https://github.com/Nordstrom/artillery-plugin-influxdb) plugin.

**Comment by gwsii** [comment]
Also, to specifically answer @erikerikson: yes, we ran both InfluxDB and Grafana on the same EC2 instance for the workshop.

**Comment by erikerikson** [comment]
Going to close this due to lack of activity.  Feel free to re-open.
