### ISSUE TITLE
slsart script command "endpoint" parameter issue

### ISSUE THREAD

**Issue by drewdresser** [Nordstrom/serverless-artillery-workshop#12]
the READme in section 2 https://github.com/Nordstrom/serverless-artillery-workshop/tree/master/Lesson2:%20Aiming%20your%20artillery says that the following command should work: `slsart script --endpoint "https://abcdefg.execute-api.eu-west-1.amazonaws.com/test/" --duration 10 -rate 5 --rampTo 15` however, when I execute that, I get the following error message:

The "url" argument must be of type string. Received type object.

**Comment by drewdresser** [comment]
This was my error. I was missing a dash before `-rate 5`.

**Comment by erikerikson** [comment]
Thanks for the update!  Happy smashing!
